name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-jvm:
    # prevent from running on forks
    if: github.repository_owner == 'restatedev'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm-version: [ 17 ]

    steps:
      - uses: actions/checkout@v3

      - name: Use JVM ${{ matrix.jvm-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jvm-version }}

      # When adding a new example make sure it's listed here
      - name: Test Java Gradle Template
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          build-root-directory: templates/java-gradle
      - name: Test java/food-ordering
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          build-root-directory: end-to-end-applications/java/food-ordering/app
      - name: Test java/patterns/sagas
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          build-root-directory: patterns-use-cases/sagas/sagas-java
      - name: Test java/tour-of-restate
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          build-root-directory: tutorials/tour-of-restate-java
      - name: Test Kotlin Template
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          build-root-directory: templates/kotlin-gradle
      - name: Build Scala Template
        run: sbt -v +package
        working-directory: templates/scala-sbt

  build-ts:
    # prevent from running on forks
    if: github.repository_owner == 'restatedev'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
      - run: npm run -ws build
